// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAzaX0RPW4r6976wpg2I2daOtjdvMxa8LY',
    appId: '1:513816233233:web:bd7b3ab78709ea399278b0',
    messagingSenderId: '513816233233',
    projectId: 'store-app-bfb84',
    authDomain: 'store-app-bfb84.firebaseapp.com',
    storageBucket: 'store-app-bfb84.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB1j5Pp60BjGgTXZpQDMecmtTBbXhVeT_w',
    appId: '1:513816233233:android:bac6406d6fd9312c9278b0',
    messagingSenderId: '513816233233',
    projectId: 'store-app-bfb84',
    storageBucket: 'store-app-bfb84.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBVOTM2s88nAP3U-pHAxPkpd0i09kt0krA',
    appId: '1:513816233233:ios:c464f04fff7b754b9278b0',
    messagingSenderId: '513816233233',
    projectId: 'store-app-bfb84',
    storageBucket: 'store-app-bfb84.appspot.com',
    iosBundleId: 'com.example.appStore',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBVOTM2s88nAP3U-pHAxPkpd0i09kt0krA',
    appId: '1:513816233233:ios:509fb52f89dad01f9278b0',
    messagingSenderId: '513816233233',
    projectId: 'store-app-bfb84',
    storageBucket: 'store-app-bfb84.appspot.com',
    iosBundleId: 'com.example.appStore.RunnerTests',
  );
}
